services:
  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    container_name: filebeat
    restart: always
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../nginx/logs:/var/log/nginx:ro # Nginx 로그 읽기
    networks:
      - 8llow8llowme-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  8llow8llowme-net:
    driver: bridge
