[Definition]
# PHP/ASP 같은 존재하지 않는 스크립트 파일 요청 차단
failregex = ^<HOST> -.*"(GET|POST).*\.php.*HTTP.*" 
            ^<HOST> -.*"(GET|POST).*\.asp.*HTTP.*" 
            ^<HOST> -.*"(GET|POST).*\.exe.*HTTP.*" 
            ^<HOST> -.*"(GET|POST).*\.pl.*HTTP.*"
ignoreregex =