[Definition]
# PHP/ASP/EXE/PL 같은 스크립트 파일 요청
failregex = ^<HOST> .*"(GET|POST).*(/(wp-admin|wp-login|wordpress|xmlrpc|phpmyadmin|phpmyadmi|pma|test\.php|setup-config\.php|admin|login)\b).*HTTP.*" (404|403|400|301|302)
            ^<HOST> .*"(GET|POST).*wp-includes.*HTTP.*" (404|403|400|301|302)
            ^<HOST> .*"(GET|POST).*wp-content.*HTTP.*" (404|403|400|301|302)
            ^<HOST> .*"(GET|POST).*\.php.*HTTP.*" (404|403|400|301|302)
            ^<HOST> .*"(GET|POST).*owa/auth/logon\.aspx.*HTTP.*"
            ^<HOST> .*"(GET|POST).*zgrab.*HTTP.*"
            ^<HOST> .*"(GET|POST).*l9tcpid.*HTTP.*"

ignoreregex =