[Definition]
# 워드프레스, phpmyadmin, admin 등 존재하지 않는 경로 탐색 차단
failregex = ^<HOST> .*"(GET|POST).*(/(wp-admin|wp-login|wordpress|xmlrpc|phpmyadmin|phpmyadmi|pma|test\.php|setup-config\.php|admin|login)\b).*HTTP.*" (404|403|400|301|302)
            ^<HOST> .*"(GET|POST).*\.php.*HTTP.*" (404|403|400|301|302)
            ^<HOST> .*"(GET|POST).*owa/auth/logon\.aspx.*HTTP.*"
            ^<HOST> .*"(GET|POST).*zgrab.*HTTP.*"
            ^<HOST> .*"(GET|POST).*l9tcpid.*HTTP.*"

ignoreregex =
