[Definition]
# PHP/ASP/EXE/PL 같은 스크립트 파일 요청
failregex = ^<HOST> .*"(GET|POST).*\.php.*HTTP.*"
            ^<HOST> .*"(GET|POST).*\.asp.*HTTP.*"
            ^<HOST> .*"(GET|POST).*\.exe.*HTTP.*"
            ^<HOST> .*"(GET|POST).*\.pl.*HTTP.*"

ignoreregex =