services:
  fail2ban:
    container_name: fail2ban
    build:
      context: .
      dockerfile: fail2ban.Dockerfile
    restart: always
    cap_add:
      - NET_ADMIN # iptables 제어 권한
    volumes:
      - ../nginx/logs:/var/log/nginx:ro # Nginx 로그 읽기 전용
    networks:
      - 8llow8llowme-net

networks:
  8llow8llowme-net:
    name: 8llow8llowme-net
    driver: bridge
