services:
  fail2ban:
    container_name: fail2ban
    image: fail2ban-fail2ban:latest
    build:
      context: .
      dockerfile: fail2ban.Dockerfile
    restart: always
    cap_add:
      - NET_ADMIN # iptables 제어 권한
    volumes:
      - ../nginx/logs:/var/log/nginx:ro # Nginx 로그 읽기
      - ./logs:/var/log # fail2ban 자체 로그 저장
    networks:
      - 8llow8llowme-net

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

networks:
  8llow8llowme-net:
    name: 8llow8llowme-net
    driver: bridge
