- labels:
    project: bosspickseoul
    env: dev
    host: backend-1
    service: service-discovery
  targets:
    - 192.168.0.13:6761
- labels:
    project: bosspickseoul
    env: dev
    host: backend-1
    service: api-gateway
  targets:
    - 192.168.0.13:6000
- labels:
    project: bosspickseoul
    env: dev
    host: backend-1
    service: auth-service
  targets:
    - 192.168.0.13:6081
- labels:
    project: bosspickseoul
    env: dev
    host: backend-1
    service: district-service
  targets:
    - 192.168.0.13:6082
- labels:
    project: bosspickseoul
    env: dev
    host: backend-1
    service: commercial-service
  targets:
    - 192.168.0.13:6083
- labels:
    project: bosspickseoul
    env: dev
    host: backend-1
    service: ai-service
  targets:
    - 192.168.0.13:6085
- labels:
    project: bosspickseoul
    env: dev
    host: backend-1
    service: community-service
  targets:
    - 192.168.0.13:6086
