# 압축 안 함
nocompress
# 로그파일 없으면 무시
missingok
# 새 로그 권한
create 0640 root root

# access.log 설정
/var/log/nginx/access.log {
    # 하루 단위 회전
    daily
    # 날짜 접미사 추가
    dateext
    # YYYYMMDD 형식
    dateformat -%Y%m%d
    # 14일 보관
    rotate 14
    sharedscripts
    postrotate
        # 회전 후 nginx 로그 reopen
        docker exec nginx nginx -s reopen
    endscript
}

# error.log 설정
/var/log/nginx/error.log {
    daily
    dateext
    dateformat -%Y%m%d
    rotate 14
    sharedscripts
    postrotate
        docker exec nginx nginx -s reopen
    endscript
}