# Logrotate 설정 (Nginx 로그 대상)
# - access.log / error.log 파일 매일 회전
# - 14일 보관 후 자동 삭제
# - 회전 후 nginx 로그 reopen

nocompress            # 압축 비활성화 (문제 분석 시 빠른 확인 목적)
missingok             # 로그파일 없으면 무시
create 0640 root root # 새 로그 생성 시 권한 설정

# access.log 설정
/var/log/nginx/access.log {
    daily
    dateext
    dateformat -%Y%m%d
    rotate 14
    sharedscripts
    postrotate
        docker exec nginx nginx -s reopen
    endscript
}

# error.log 설정
/var/log/nginx/error.log {
    daily
    dateext
    dateformat -%Y%m%d
    rotate 14
    sharedscripts
    postrotate
        docker exec nginx nginx -s reopen
    endscript
}