# api.tripmarble.com (HTTP -> HTTPS 리다이렉트)
server {
    listen 80;
    server_name api.tripmarble.com;

    # Let's Encrypt 인증서 발급용
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://api.tripmarble.com$request_uri;
    }
}

# api.tripmarble.com (API 서버 처리)
server {
    listen 443 ssl;
    server_name api.tripmarble.com;

    ssl_certificate /etc/letsencrypt/live/api.tripmarble.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.tripmarble.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # 업로드 요청 최대 크기
    client_max_body_size 150M;

    # 인증/인가, 회원 서비스 -> 8081, /auth-service/와 그 하위 모두 매칭
    location /auth-service/ {
        proxy_pass http://192.168.0.46:8081/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API Gateway -> 8000, /api-gateway/와 그 하위 모두 매칭
    location /api-gateway/ {
        proxy_pass http://192.168.0.46:8000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
