server {
    listen 80;
    server_name www.tripmarble.com;

    # 도메인별 access log
    access_log /var/log/nginx/tripmarble_access.log main;

    # index.html 캐싱 완전 방지
    location = /index.html {
        proxy_pass http://minio:9000/tripmarble/client/index.html;
        expires    -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        add_header Pragma       "no-cache";
        add_header Expires      0;
    }

    # 정적 파일 및 SPA 라우팅 (History API fallback)
    location / {
        # MinIO 버킷(tripmarble)의 모든 요청을 그대로 전달
        proxy_pass http://minio:9000/tripmarble/client;
        # 원본 요청 헤더 전달
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        try_files $uri $uri/ /index.html; # 파일이 없으면 index.html로 포워딩
    }

    # location /api {
    #     proxy_pass http://api-gateway:8080; # 추후에 해당 서비스의 백엔드 관련 사설 IP로 할당해서 매핑하는 것으로 변경
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }
}
