server {
    listen 80;
    server_name www.tripmarble.com;

    # access log
    access_log /var/log/nginx/tripmarble_access.log main;

    # Let's Encrypt challenge 파일 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 나머지는 HTTPS로 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.tripmarble.com;

    ssl_certificate /etc/letsencrypt/live/www.tripmarble.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.tripmarble.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/tripmarble_ssl_access.log main;

    # Next.js SSR 서버로 프록시
    location / {
        proxy_pass http://web-ssr:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 인증/인가, 회원 서비스 -> 8081, /auth-service/와 그 하위 모두 매칭
    location /auth-service/ {
        rewrite ^/auth-service(/.*)$ $1 break;
        proxy_pass http://192.168.0.46:8081;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API Gateway -> 8000, /api-gateway/와 그 하위 모두 매칭
    location /api-gateway/ {
        rewrite ^/api-gateway(/.*)$ $1 break;
        proxy_pass http://192.168.0.46:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
