global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          instance: deploy
          project: infra

  - job_name: node
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/nodes.yml

  - job_name: bosspickseoul-cloud
    metrics_path: /actuator/prometheus
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/bosspickseoul-cloud-*.yml

  - job_name: bosspickseoul-service
    metrics_path: /actuator/prometheus
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/bosspickseoul-service-*.yml
