services:
  jenkins:
    container_name: jenkins
    restart: always
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - '49999:8080'
      - '50000:50000'
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - 8llow8llowme-net

networks:
  8llow8llowme-net:
    name: 8llow8llowme-net
    driver: bridge
