services:
  vault:
    image: ${VAULT_IMAGE}
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_API_ADDR: ${VAULT_API_ADDR}
      TZ: ${TZ}
    ports:
      - '${VAULT_PORT}:8200'
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
      - ./docker-entrypoint-vault.sh:/usr/local/bin/docker-entrypoint-vault.sh:ro
      - ./policies:/vault/policies:ro
      - ./scripts:/vault/scripts:ro
      - ./data:/vault/file
      - ./logs:/vault/logs
    entrypoint:
      - sh
      - /usr/local/bin/docker-entrypoint-vault.sh
    networks:
      - 8llow8llowme-net
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

networks:
  8llow8llowme-net:
    name: 8llow8llowme-net
    driver: bridge
